package com.hafiz.spring.springcrudpostgres.controller;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.hafiz.spring.springcrudpostgres.entity.Bank;
import com.hafiz.spring.springcrudpostgres.repository.BankRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/bank") // This means URL's start with /demo (after Application path)
public class BankController {

	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private BankRepository bankRepository;	
	
	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewBank (@RequestParam String id
		, @RequestParam String name) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		
		
		Bank b = new Bank();
		b.setBankId(id);
		b.setBankName(name);
		bankRepository.save(b);
		return "Saved";
	}	

	@GetMapping(path="/all")
	public @ResponseBody Iterable<Bank> getAllBanks() {
		// This returns a JSON or XML with the banks
		return bankRepository.findAll();
	}		
	
	
	@GetMapping(path="/allj")
	public String getAllBankswithJasper(Model model) {
		
		Iterable<Bank> bankList = bankRepository.findAll();

		List<Bank> list = new ArrayList<Bank>();
		for (Bank s : bankList) {			
			list.add(s);
	    }
		

		model.addAttribute("merchantName", "Toko Mudah Barokah");
		model.addAttribute("banks", list);

		return "bank";
		
	}	
	
}
